### ISSUE TITLE
Cell count doesn't update

### ISSUE THREAD

**Issue by chisquared** [ticoneva/pystata-kernel#1]
First of all, thank you for writing this improved implementation of pystata! It is so nice to not have to type `%%stata` over and over again... I will be sharing this with my colleagues.

Quick bug report: in the current version of pystata-kernel, I find that the cell count remains fixed at [1], even when I run cells directly after each other. I wondered if you have noticed the same, or if it's unique to my setup (running on Linux). 

![image](https://user-images.githubusercontent.com/7705545/161772221-d6c78850-a9d7-43c0-8582-792b71706eae.png)

**Comment by chisquared** [comment]
This seems to happen because of using IPythonKernel instead of the more general Kernel; addressed in #2.

**Comment by ticoneva** [comment]
Sorry for the late reply---it's the end of semester and I am overwhelmed with teaching. I just checked and indeed the count isn't incrementing. I will try out your commit once I get back to my office after the weekend and push to PyPI if everything checks out.

**Comment by ticoneva** [comment]
I have merged the commit. I only change I made after the merge was to change the indentation of the two new lines from tabs to spaces. Thanks for the commit!
