### ISSUE TITLE
Unexpected errors in one-line code cells with comments

### ISSUE THREAD

**Issue by gaksaray** [ticoneva/pystata-kernel#26]
`pystata-kernel` (v.0.3.1) produces unexpected errors for inline comments starting with `\\`.

<img width="945" alt="comments" src="https://github.com/ticoneva/pystata-kernel/assets/72267919/624f4bab-82e2-4502-986b-8d02f2456210">

In the example above, third and fourth cells produces two different errors: "_b not allowed when e(b) is not present" and "/ is not a valid command name". The expected behavior for the third cell is to output "Hello world", and for the fourth cell to output an empty line as in the first cell.

**Comment by ticoneva** [comment]
The errors come from Stata itself, see the screen capture below. The reason this is happening is that Stata's `pystata` interface treats single-line code block as command, so `//` is invalid. The workaround for 3. is to add another line with just `//`&mdash;whitespace will not work because `pystata` trims the code block before passing it to Stata. For 4. there is no good workaround.

![image](https://github.com/ticoneva/pystata-kernel/assets/12955448/607aa477-5839-469d-a377-d01c4adcbd25)

**Comment by gaksaray** [comment]
I think my confusion arose from the fact that I almost never use Stata from the console and typically through the do-file editor. Code executed from the editor runs without errors:

<img width="1538" alt="Screenshot 2024-02-29 at 08 45 42" src="https://github.com/ticoneva/pystata-kernel/assets/72267919/1b87698d-33c8-480e-a181-09186ccf4449">

Now I can see that single-line code blocks with `//` comments are treated as console commands, thus producing these errors.

Interestingly, the Stata console syntax highlighting displays comments in green, which I think is inconsistent with the actual output (not to mention the error message `_b not allowed when e(b) is not present` seems somewhat cryptic):

<img width="461" alt="Screenshot 2024-02-29 at 08 49 43" src="https://github.com/ticoneva/pystata-kernel/assets/72267919/586cc288-0810-4eaa-b685-436eedc37408">

Surely this concerns Stata and not `pystata-kernel`. Thanks @ticoneva for clarification!

**Comment by hugetim** [comment]
FWIW, `nbstata` has a workaround to enable single-line comments to work:
<img width="446" alt="image" src="https://github.com/ticoneva/pystata-kernel/assets/8237868/94219e22-3b5e-4b8c-add5-09dbf8834dee">

This is the function being used under the hood, if you wanted to do something similar: https://github.com/hugetim/nbstata/blob/master/nbstata/code_utils.py#L77

But there's always the potential for unintended consequences of such a workaround, and there's merit to pystata's approach of staying closer to Stata's native behavior.

**Comment by ticoneva** [comment]
Indeed, I think we have had this discussion before. It is safer to have one option that has more advanced features (`nbstata`) and one that stays as close as possible to the official `pystata` interface.  I am going to edit `pystata-kernel`'s readme to make this more clear.
