### ISSUE TITLE
Kernel doesn't start

### ISSUE THREAD

**Issue by rhstanton** [ticoneva/pystata-kernel#3]
This is a great idea, but Stata doesn't seem to start on my machine (macOS 12.5). When I open a new Jupyter notebook and try to run "disp 2", there's no output in the notebook and the Jupyter window shows:

```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/stanton/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 367, in dispatch_shell
    await result
  File "/Users/stanton/anaconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 657, in execute_request
    reply_content = self.do_execute(
  File "/Users/stanton/anaconda3/lib/python3.9/site-packages/pystata-kernel/kernel.py", line 36, in do_execute
    stata_setup.config(env['stata_dir'],env['edition'])
  File "/Users/stanton/anaconda3/lib/python3.9/site-packages/stata_setup.py", line 41, in config
    raise OSError(path + " is not Stata's installation path")
OSError: /Applications/Stata/StataMP.app/Contents/MacOS is not Stata's installation path
```

**Comment by ticoneva** [comment]
The path detection algorithm is inherited from `stata_kernel`. Do you know if `/Applications/Stata/StataMP.app/Contents/MacOS` is truly the location your Stata executable?

**Comment by rhstanton** [comment]
Yes, it is:

```
Richards-MacBookPro:~ stanton$ ls /Applications/Stata/StataMP.app/Contents/MacOS
StataMP  libstata-mp.dylib  stata-mp
Richards-MacBookPro:~ stanton$ 
```

**Comment by rhstanton** [comment]
I got it working and graphs display! I just created a file ```~/.pystata-kernel.conf``` with the following contents:

```
[pystata-kernel]
stata_dir = /Applications/Stata
edition = mp
graph_format = svg
echo = True
```

Thanks!

**Comment by ticoneva** [comment]
It appears that pystata only requires the path `/Applications/Stata` instead of the actual path of the executable. I will need to test this with a Mac, but if that's really the case I will change the code accordingly.
