### ISSUE TITLE
Feature request: expose 'splash' parameter of pystata.config.init via config file

### ISSUE THREAD

**Issue by ideabucket** [ticoneva/pystata-kernel#5]
According to the pystata documentation, [`pystat.config.init` has a `splash` parameter][1] which, when set to `False`, suppresses the splash screen with the version, license, etc. information. 

[1]: https://www.stata.com/python/pystata/config.html#pystata.config.init

It would be great if this was available as a config file parameter.

Thanks!

**Comment by ticoneva** [comment]
Version 0.1.20 accepts `splash = False`, which suppresses display of the splash message.
