### ISSUE TITLE
New echo = None option chokes on multiline commands

### ISSUE THREAD

**Issue by ideabucket** [ticoneva/pystata-kernel#6]
Sorry to report that the new `echo = None` behaviour breaks the kernel in a couple of scenarios:

1. Any command extended across multiple lines with `///` raises an exception:

```stata
sysuse auto
tab mpg ///
    foreign
```
> ```
> Exception in thread Stata:
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "/usr/local/stata17/utilities/pystata/core/stout.py", line 176, in run
>     raise SystemError(output)
> SystemError: (1978 automobile data)
> variable noisily not found
> r(111);
>```

2. So does any use of the `#delimit` directive:

```stata
#delimit ;

regress mpg
    rep78
    foreign

#delimit cr
```
> ```
> Exception in thread Stata:
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "/usr/local/stata17/utilities/pystata/core/stout.py", line 176, in run
>     raise SystemError(output)
> SystemError: # is not a valid command name
> r(199);
>```

Let me know if l can provide more detail.

**Comment by ticoneva** [comment]
Handling such cases would require porting `stata_kernel`'s `CodeManager` class with significant changes. Since this will take significant effort, I am removing this feature until it actually works.
