### ISSUE TITLE
Magics?

### ISSUE THREAD

**Issue by roblem** [ticoneva/pystata-kernel#9]
Wondering about the possibility of adding the `%mata`, `%browse`, `%head`, and `%tail` magics.

So far this semester, things are going well with pystata-kernel (no students are complaining and things work).

**Comment by ticoneva** [comment]
Magics are not part of Stata syntax, which is why `pystata-kernel` does not support them. The official `stata_setup` does come with magic support. Is there a reason why it does not work for you?

**Comment by roblem** [comment]
Thanks,

If by official `stata_setup` you mean running stata commands inside a python codeblock with a python kernel, I suppose they do work but I haven't tried it recently.  My students are using the `pystata-kernel` and I am trying to keep them away from anything python so they are using stata syntax only method by using a `pystata-kernel` stata kernel. 

For my students who are used to browsing data in the stata program window, there is no convenient analog with `pystata-kernel` (with a `pystata-kernel` stata kernel you could execute a stata `list` command but for large datasets this is impractical). `stata-kernel` had a `%browse` magic that would all students to browse large datasets in an html window with scroll bars.  The other magics are nice but don't add too much in my experience.

**Comment by ticoneva** [comment]
The way `stata-kernel` does this is:
1. compose a Stata command to save data in CSV format. 
2. Save the in a temporary .do file and run it.
3. Open the CSV file with `pandas`.

The nice HTML formatting is native `pandas`. Since `pystata` does provide a way to transfer data between Stata and Python, we could do something similar. 

As a matter of principle though, I am still not sure whether it is a good idea to introduce the magic syntax into an otherwise native Stata environment. As a reference, `irkernel` [does not support magics](https://irkernel.github.io/faq/) either.

**Comment by roblem** [comment]
I see your point. Maybe a decent workaround is this:

```stata
set linesize 200
list, clean
```
Then you can write click on the output section and "Enable Scrolling for outputs" (note this only fixes vertical scrolling, not horizontal).  This yields:

![image](https://user-images.githubusercontent.com/1871086/188121855-ce2dc5d1-51ae-4bd7-99d5-da1d6b37fba7.png)

When you hover over the data output area, the vertical scrollbar will let you browse the data.

**Comment by roblem** [comment]
I tried to call python code from within the pystata-kernel to see if the `head` command from pandas is feasible.  If it is feasible I was thinking of writing a few stata functions that pass info to python and produce html output.

```
sysuse auto

python:
import pandas as pd
import numpy as np
df = pd.DataFrame(Data.get())
end

python:
print(df.head())
end
```
This produces not output and no errors.  If I use the python print statement, I get output:
```
python:
print(df.head())
end
```
gives this
```
. 
. python:
----------------------------------------------- python (type end to exit) ------
>>> print(df.head())
              0     1   2              3    4   ...   7   8    9     10  11
0    AMC Concord  4099  22   3.000000e+00  2.5  ...  186  40  121  3.58   0
1      AMC Pacer  4749  17   3.000000e+00  3.0  ...  173  40  258  2.53   0
2     AMC Spirit  3799  22  8.988466e+307  3.0  ...  168  35  121  3.08   0
3  Buick Century  4816  20   3.000000e+00  4.5  ...  196  40  196  2.93   0
4  Buick Electra  7827  15   4.000000e+00  4.0  ...  222  43  350  2.41   0

[5 rows x 12 columns]
>>> end
```
So the data is being loaded into python and we can print things going to the text based stata console which display in jupyter.  Maybe `pystata-kernel` has no html handling capabilities, which is why `df.head()` produces no output??  Not sure.

**Comment by ticoneva** [comment]
I have started implmenting magics. Currently two magics are supported: `*%browse` and `*%help`. To stay compatible with `stata-kernel`, you can also start magics with `%`, but this will cause errors when the notebook is exported and run as a Stata script. 

To try it out, install the newest version from Github:

```
pip install git+https://github.com/ticoneva/pystata-kernel.git
```

Let me know if it works as intended.

The process of implementing magics is going to take time, as code from `stata-kernel` needs to be integrated with `pystata` on a case-by-case basis.

**Comment by roblem** [comment]
Thanks for this!

- `%browse` works fine once pandas is installed in the python environment (see pull request).
- `%help` hangs with this error in jupyter server console:
   ```
   Traceback (most recent call last):
  File "/home/user/anaconda/envs/econ407/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/home/user/anaconda/envs/econ407/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 721, in execute_request
    reply_content = self.do_execute(
  File "/home/user/anaconda/envs/econ407/lib/python3.10/site-packages/pystata-kernel/kernel.py", line 86, in do_execute
    code = self.magic_handler.magic(code,self)
  File "/home/user/anaconda/envs/econ407/lib/python3.10/site-packages/pystata-kernel/magics.py", line 61, in magic
    code = getattr(self, "magic_" + name)(code, kernel)
  File "/home/user/anaconda/envs/econ407/lib/python3.10/site-packages/pystata-kernel/magics.py", line 164, in magic_help
    with open(self.csshelp_default, 'r') as default:
  FileNotFoundError: [Errno 2] No such file or directory: /home/user/anaconda/envs/econ407/lib/python3.10/site-packages/pystata-kernel/css/_StataKernelHelpDefault.css
   ```
   which I can see exists in the repository but doesn't get installed with `pip install git+https://github.com/ticoneva/pystata-kernel.git`

**Comment by roblem** [comment]
To fix the css problem, maybe manifest.in should be
```
include README.md
include pystata-kernel/logo-64x64.png
include pystata-kernel/css/_StataKernelHelpDefault.css
```
Not totally sure.

**Comment by ticoneva** [comment]
Thanks for the feedback. `pandas` and `beautifulsoup4` have been added as dependencies and `pystata-kernel/css` has been added to the manifest.

**Comment by roblem** [comment]
Thanks for all the work over the past few weeks.  We have `pystata-kernel` running on a campus jupyterhub server and things are working well.

The only marginally useful magic (and it is pretty marginal as it only saves having to write `end` at the end of mata blocks) that is still not implemented from my perspective is `%mata`.  `pystata-kernel` needs all mata commands wrapped like this:
```
mata
mata describe
end
```
The magic would allow that code to appear as
```
%mata
mata describe
```
Note there is no `end`.  The magic processor would need to 
1. Take the `arg['code']` strip out the `%` and append an end:
    ``` 
   mata
   mata describe
   end
   ``` 
   Maybe something like: `code = code.replace('\n%','') + '\n' + 'end'`
2. Take this clean code, submit to the kernel and pass back output (not sure how to do this) 

To me it is a minor convenience to be able to skip typing in `end` because in class, I always forget to add it as I am explaining other things.  I can understand if something like this doesn't get implemented however.

**Comment by ticoneva** [comment]
Implementing the mata cell magic is quite straightforward, but it will break .do file export. This is because even if Stata ignores the magic itself, the mata code that comes after it will not be enclosed in the correct way. We can write a custom `nbconvert` export option to do some conversion, but I am not sure this is worth the effort.

**Comment by roblem** [comment]
Thanks. It makes sense. Closing.
